### PR TITLE
Including URL on route

### LINKED ISSUE #705: Wallet not being disconnected when change the chain
**Describe the bug**
The wallet is not being disconnected when the User changes the network.

**To Reproduce**
1. Connect to a wallet in a specific chain.
2. Change to another chain.
3. The previous wallet continues logged in and the user start to see some errors on the system.

**Expected behavior**
The system should disconnect the wallet and ask to connect in the new network

**Screenshots**
https://github.com/telosnetwork/open-block-explorer/assets/4021973/04e908e4-705c-485b-9549-709d1140b868

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 (a)
 - Browser: Chrome
 - Version: 113.0.5672.126

### LINKED ISSUE #709: Improve router to include chain name on the URL
## Description

Improve router to  **always** include the chain name on the URL to allow users to share links directly to a specific chain.

URL should be something like https://_domain_/_chain_/... or https://_domain_/?network=_chain_

We should make sure that however the user gets to OBE, the network is always required.

### LINKED ISSUE #720: [SPIKE] Investigate how OBE will behave with multiple tabs in different chains
Investigate how the system will behave when having multiple tabs opened in different chains:

- Will UAL handle multiple logins?
- How will work the local storage vars?
- Will different tabs interfere in each other?

### PR DESCRIPTION
**Pull request by jaegerfe**
# Fixes #709

## Description

Include network on route.

- Included a 'beforeRoute' on router to watch the param and change the system accordingly to the network on the URL
- Included a reactive state for route data to be able to listen URL changes
- Watching route data on MainLayout to live update Theme without the necessity of reload all application
- Creating some IDs for local storage variables resolved the issue to have more than one chain opened in the same browser. Fixes #705. Fixes #720.

## Test scenarios

- Tested changing network using MultiChain component;
- Tested changing network on URL;
- Tested getting a link form another network;

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have tested for mobile functionality and responsiveness

### CODE REVIEW

**Review by donnyquixotic — CHANGES_REQUESTED** [review]
@jaegerfe 
network switching via URL param does not persist. If you load the link below you will see the correct network flash then reload the default network (in this case, telos). 
https://deploy-preview-717--open-block-explorer.netlify.app/?network=eos

**Comment by jaegerfe** [comment]
@donnyquixotic could you please take a look again? I think I solved the issue! I will continue testing on my side and see if there is anything else weird.

**Comment by donnyquixotic** [comment]
> @donnyquixotic could you please take a look again? I think I solved the issue! I will continue testing on my side and see if there is anything else weird.

I'm experiencing the same behavior.

**Comment by jaegerfe** [comment]
> > @donnyquixotic could you please take a look again? I think I solved the issue! I will continue testing on my side and see if there is anything else weird.
> 
> I'm experiencing the same behavior.

Did you used the latest changes? Using this link https://refactor-router.open-block-explorer.pages.dev/ we can't see this behavior anymore...

**Review by donnyquixotic — APPROVED** [review]
@jaegerfe working for me now! can you change the target branch for the PR to 'develop' and resolve any conflicts? We can merge incremental progress there and do a feature release PR to master when it's ready.

**Comment by jaegerfe** [comment]
> @jaegerfe working for me now! can you change the target branch for the PR to 'develop' and resolve any conflicts? We can merge incremental progress there and do a feature release PR to master when it's ready.

Sure! I will just update some description and update the refs.

**Review by karynemayer — APPROVED** [review]

**Pull request merged**
