### PR TITLE
752 cant sign an msig proposal with owner key

### LINKED ISSUE #752: Can't sign an msig proposal with owner key
**Describe the bug**
Telos Explorer will not allow me to sign an msig updateauth proposal with an owner key.   It defaults the key back to active which results in an assertion error.

**To Reproduce**
1. Go to https://explorer-test.telos.net/proposal/updateactivf
2. This transaction should be called updateowner,  its updates the owner keys of bennyfitokent1
3. Even thought I'm logged in as key1bennyfi1@owner,  when I go to execute the transactions, it defaults to key1bennyfi1@active
resulting in an assertion error.   
5. I reported this to Anchor,  thinking it was their issue,  but here's their response.
"I spoke with our team regarding this and it turns out the issue resides with the block explorer. Regardless of the account/permission you sign in with to the block explorer, the explorer itself is forcing the msig “approval” to use the accounts active permission, so then when its routed to Anchor, it pops up the active permission.  You can checkout the code for the block explorer here - https://github.com/telosnetwork/open-block-explorer/blob/ac8ed50add1cf1557bce40b7596dd28d48c69539/src/pages/ProposalItem.vue#L355 

Anyhow, this is not something that we can repair on our end, so i would suggest reaching out to the Telos support team for their block explorer and see what they recommend as a solution,  We'll be reaching out as well, but the more people bring up the issue, the more they are likely to fix it.
If there's anything else we can help you with, please let us know."

**Expected behavior**
I log in as owner to approve a msig,  I need to be able to sign as owner.

**Screenshots**
msig3
msig1
msigissue2signing
msig4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  windows
 - Browser [e.g. chrome, safari]  Brave

**Additional context**
We're hardening our treasury security with Ledger wallets.   We need to be able to add and remove owner keys to our system accounts.   We are using a similar account structure to Telos's eosio account.   Can you suggest a work around for this that will allow us to still use HW wallets?  How do you handle this on the eosio account?

### PR DESCRIPTION
**Pull request by donnyquixotic**
# Fixes #752

## Description

see Issue

## Test scenarios
- see Issue for main testing scenarios
- test delegate resources using 'owner' permission

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

### CODE REVIEW

**Comment by donnyquixotic** [comment]
@cuvialabs do you mind testing to make sure this is resolved for you using the [testnet deploy link](https://deploy-preview-753--obe-testnet.netlify.app/)? Thanks!

**Comment by cuvialabs** [comment]
Same result,  its switching to the active key by default and will not let me sign as owner.

image

**Review by karynemayer — CHANGES_REQUESTED** [review]
uuh, thank you for including the permissions properly!

I was able to make a transfer msig successfully with my owner permission.
However, I'm seeing this error when trying to upload a file:
Screenshot 2023-09-13 at 14 30 48

The error doesn't exist on current deployed version.

**Comment by donnyquixotic** [comment]
> Same result, its switching to the active key by default and will not let me sign as owner.
> 
> image

Were you using this link: https://deploy-preview-753--obe-testnet.netlify.app/ ? Can you try logging out, clearing cache and creating a _new_ test proposal and see if you can reproduce the same behavior? I've tested using a simple action on a new proposal and correctly prompts using 'owner' permission.

**Comment by cuvialabs** [comment]
Still can't sign with the owner key.   It is defaulting to the user key.   Here's what's happening

1/ Environment
Windows 10 version 22H2
Brave Browser [Version 1.58.129 Chromium: 117.0.5938.88 (Official Build) (64-bit)](https://brave.com/latest/)
Anchor Desktop Wallet 1.3.12
Ledger Nano X version 2.2.2


1/ When I go connect to the testnet explore https://explorer-test.telos.net/proposal/updateactivh  .   Anchor defaults to the active key.

https://explorer-test.telos.net/proposal/updateactivh

2/ I manually change this to the owner key  
image

3/ I created this msig transaction 
 cleos --url=https://testnet.telos.caleos.io multisig propose updateactivh '[{"actor":"key1bennyfi1","permission":"owner"}, {"acto
r":"key2bennyfi2","permission":"owner"}, {"actor":"key3bennyfi3","permission":"owner"}]' '[{"actor":"bennytokent1","permission":"owner"}]' eosio updateauth '{"a
ccount": "bennytokent1", "permission": "owner", "parent": "", "auth": {"threshold": 1, "accounts": [{"permission": {"actor":"ownerbennyfi","permission":"owner"}
, "weight": 1}], "keys": [], "waits": []}}' cfoxxxxxxxxx 164

4/  I attempt to sign this transaction with owner key
image

5/ Anchor defaults back to active key.   I reported this to Greymass and they reviewed the explorer source and determined the problem was within the explorer.   They told me they would reach out to you. 

image

Here's the raw transaction details
{
"expiration":"2023-09-21T15:57:09"
"ref_block_num":50539
"ref_block_prefix":2693336511
"max_net_usage_words":0
"max_cpu_usage_ms":0
"delay_sec":0
"context_free_actions":[]
"actions":[
0:{
"account":"eosio.msig"
"name":"approve"
"authorization":[
0:{
"actor":"key1bennyfi1"
"permission":"active"
}
]
"data":{
"proposer":"cfoxxxxxxxxx"
"proposal_name":"updateactivh"
"level":{
"actor":"key1bennyfi1"
"permission":"active"
}
"proposal_hash":NULL
}
}
]
"transaction_extensions":[]
}


6/ Reply from Greymass team 
Hello,

I spoke with our team regarding this and it turns out the issue resides with the block explorer. Regardless of the account/permission you sign in with to the block explorer, the explorer itself is forcing the msig “approval” to use the accounts active permission, so then when its routed to Anchor, it pops up the active permission.  You can checkout the code for the block explorer here - https://github.com/telosnetwork/open-block-explorer/blob/ac8ed50add1cf1557bce40b7596dd28d48c69539/src/pages/ProposalItem.vue#L355 

Anyhow, this is not something that we can repair on our end, so i would suggest reaching out to the Telos support team for their block explorer and see what they recommend as a solution,  We'll be reaching out as well, but the more people bring up the issue, the more they are likely to fix it.
If there's anything else we can help you with, please let us know.
 
-Tony


6/ Really,  really,  really need this to work.

**Comment by donnyquixotic** [comment]
@cuvialabs  I think there may still be some confusion. You can see a successfful sign using owner permissions here: The hard-coded 'active' permissions pointed out by the greymass team should be resolved but can only be tested using the deploy link associated with this PR as they have not been merged yet. (You won't be able to test using the production testnet link). In order to rule some things out, can you confirm the following: https://deploy-preview-753--obe-staging.netlify.app/proposal/ownersign1?network=telos
- [ ] You are using the _deploy_ link: https://deploy-preview-753--obe-staging.netlify.app to test signing **_not_** https://explorer-test.telos.net/
- [ ] You are unable to sign w/owner permission using a _non-ledger account_ 

Feel free to reach out to me on telegram for quicker turnaround: @donnyquixotic

**Comment by karynemayer** [comment]
@donnyquixotic  
to reproduce the file upload failure:
- create a new proposal
- download the sample csv ( feel free to edit it or not - it should be able to read it and show errors of account not found in the ui)
- try to upload it
- button `upload` does nothing and generates the error

**Comment by cuvialabs** [comment]
Looks like this is fixed,  but awaiting a pull request approval.   Any update on that?  Its been 3 weeks.

**Comment by cuvialabs** [comment]
THANK YOU!!

**Pull request closed without merging**
