### PR TITLE
Better filters for transaction table

### LINKED ISSUE #547: Scoped search should consider all transactions
## Overview
When applying the search and the filters that are scoped to the account's transaction, it only considers the current page.

## Steps to reproduce
1. Using the main search bar, select an account such as `tf` 
2. Try any filter
3. See it that only applies to the current page

## Acceptance criteria
* The selected filters should be applied to all transactions, providing a new list of pages containing only filtered transactions
* For better performance, consider grouping all filters and creating an `Apply Filters` button to start filtering the account's transaction.
* Latest transactions label should appear only once, i.e. remove the one below

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #547, #570, #549, #588
## Description 

Previously, the transaction table filters were not functioning as expected. To improve the user experience, more intuitive filter components were implemented, allowing users to easily understand and utilize the filters. Additionally, instead of solely filtering the current results, a new query is now initiated with the updated filter parameters.

Another issue that was addressed was the pagination buttons at the bottom of the table scrolling horizontally off the screen when the table width exceeded the viewport. This issue has been resolved to ensure a seamless user experience.

## Test scenarios

**NOTE**: this only works on **[Mainnet](https://547-scoped-search-should-con.open-block-explorer.pages.dev/)** because we don't have enough tokens (actually zero) and Hyperion-dev does not use the query param _notified_ so the account filter does not wor on Testnet.

Scenario: Filter by Account
- Click on the "Accounts" button
- Partially type a name and select an account from the dropdown list
- The button should change to a secondary color (blue), the button text should include the name of the selected account, and a new page should load displaying only the transactions associated with that account.

Scenario: Filter by Action Name
- Click on the "Actions" button
- Type one or more action names separated by commas
- The button should change to a secondary color (blue), the button text should include the typed action name(s), and a new page should load displaying only the transactions associated with the selected action(s).

Scenario: Filter by Date Range
- Click on the "Date" button
- Modify one or both of the selected dates
- Once the changes are complete, the button should change to a secondary color (blue), the button text should include the selected date range, and a new page should load displaying only the transactions within the selected date range.

Scenario: Filter by Tokens
- Click on the "Token" button
- Type one or two letters of the token symbol
- A dropdown list of tokens should appear
- Select one token from the list
- Once the selection is made, the button should change to a secondary color (blue), the button text should include the selected token symbol, and a new page should load displaying only the transactions associated with the selected token.

Scenario: Multiple Simultaneous Filters
- Any combination of the above scenarios should result in a group of secondary-colored buttons changing their text to reflect the applied filters. The transaction page should respect all filters at once, possibly resulting in zero results being displayed.

Scenario: Clear Filters
- Execute any of the above scenarios
- Note that a "Clear filters" button appears, containing a cross symbol and text
- Click on this button
- All filter buttons should return to their primary color (violet), and their text should return to their default label. The transaction page should contain an unfiltered list of transactions.

## Screenshots

image
image
image
image

## Checklist:
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

### CODE REVIEW

**Review by donnyquixotic — APPROVED** [review]

**Review by EJSG — APPROVED** [review]
this is a big one, really nice work!

**Comment by donnyquixotic** [comment]
@Viterbo requested changes:
- [ ]  show filter buttons on _all_ transaction table pages (including first page w/live tx updating)
- [ ] add toggle button that enables live tx updating
- [ ] disable live tx toggle on navigation from first page 
- [ ] on toggle live tx to 'true' state, if not already on first page, snap to it
- [ ]  if on first page, on click/input filter, _disable_ live tx table updating (reflect in toggle switch)

**Review by donnyquixotic — CHANGES_REQUESTED** [review]
see: https://github.com/telosnetwork/open-block-explorer/pull/575#issuecomment-1431579697

there is some buggy behavior on account tx table filtering. example: search for account, see limited or no results, then navigate 2 or more pages and unrelated transactions start displaying again.

**Review by donnyquixotic — CHANGES_REQUESTED** [review]
delete src/config/tokensList.ts

**Pull request merged**
