### PR TITLE
feat: focus search input

### LINKED ISSUE #193: BUG - keyboard does not pop up for search bar on mobile (iPhone)
**Describe the bug**
on touch search bar input, keyboard does not automatically pop-up for iPhone

**To Reproduce**
1. touch search bar input
2. see keyboard not automatically pop-up

**Expected behavior**
keyboard automatically pops up 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by WikusKriek**
# Fixes #193 

## Description

Search on iPhone should focus on one click. 
I was not able to replicate the issue, so its sort of  a blind fix.

## Checklist:

-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [ ] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages

### CODE REVIEW

**Comment by EJSG** [comment]
looks like homepage search requires 2 taps in iOS. if there is an input component/element being conditionally rendered you could try adding the `autofocus` attr, https://quasar.dev/vue-components/input#qinput-api (also should be valid for vanilla HTML, not just quasar)

**Review by karynemayer — CHANGES_REQUESTED** [review]
The search field still requires a second click

**Comment by donnyquixotic** [comment]
@EJSG Can you address this issue when you get the opportunity?

**Comment by EJSG** [comment]
yeah i can take a look @donnyquixotic

**Review by Viterbo — APPROVED** [review]

**Comment by EJSG** [comment]
@Viterbo did you check this on iphone specifically? it isnt working for me, i have been working on trying to fix it today with no luck

**Comment by EJSG** [comment]
Today I spent a few hours looking at this. I cannot make the keyboard pop up. iOS (safari and all other browsers, as they have to use safari engine) has nonstandard input logic which prevents the current setup from being programmatically focused. there are many many others having a similar issue, all suggested workarounds do not work for us. i think if the search bar were changed to a real text input (e.g. `q-input`) rather than a `q-select` it would work, but as it is, i don't think it is possible. refactoring to use a text input would take too long and is out of scope for me right now, maybe we can revisit in a grooming

**Pull request closed without merging**
